export enum EMPLOYEE_VERIFICATION_STATUS {
  "PENDING" = "PENDING",
  "VERIFIED" = "VERIFIED",
}

export enum EMPLOYEE_TASK_STATUS {
  "PENDING" = "PENDING",
  "DONE" = "DONE",
  "CANCELLED" = "CANCELLED",
}
